import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import Employee from "../models/Employee.js";


export const login = async (req, res) => {
    try {
        const { email, password } = req.body;

        if (!email || !password)
            return res.status(400).json({ message: "Email and Password are required" });

        // Find user by email and check if portal access is enabled
        const user = await Employee.findOne({
            email: email,
            enablePortalAccess: true
        });

        if (!user) 
            return res.status(404).json({ message: "User not found or portal access not enabled" });

        // Check if password exists
        if (!user.password) {
            return res.status(401).json({ message: "Password not set for this user" });
        }

        // Compare password
        const validPassword = await bcrypt.compare(password, user.password);
        if (!validPassword)
            return res.status(401).json({ message: "Invalid credentials" });

        // Generate JWT token
        const token = jwt.sign(
            { id: user._id },
            process.env.JWT_SECRET,
            { expiresIn: "7d" }
        );

        return res.status(200).json({
            message: "Login successful",
            token,
            user: {
                name: `${user.firstName} ${user.lastName}`,
                email: user.email,
            },
        });
    } catch (error) {
        return res.status(500).json({ message: error.message });
    }
};


//her is hashed password compared so we have to set the password hash when the user generated by the admin 